- name: Load modules
  modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_sh
    - nf_conntrack_ipv4
    - br_netfilter

- name: Auto load modules
  lineinfile: path=/etc/modules line='{{ item }}' create=yes state=present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_sh
  - nf_conntrack_ipv4
  - br_netfilter
